apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nameService" . }}
  labels:
    app: {{ template "nameService" . }}
    service: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "nameService" . }}
      service: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ template "nameService" . }}
        service: {{ .Chart.Name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "80"
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "3"
          - name: attempts
            value: "2"
          - name: timeout
            value: "1"
          - name: single-request
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: service
                      operator: In
                      values:
                        - {{ .Chart.Name }}
                    - key: type
                      operator: In
                      values:
                        - webserver
                topologyKey: kubernetes.io/hostname
      containers:
      - name: {{ template "nameService" . }}
        image: {{ .Values.global.image }}
        imagePullPolicy: Always
        {{- if .Values.containerResources }}
        {{- if .Values.containerResources.sv }}{{ toYaml .Values.containerResources.sv | trim | nindent 8 }}{{- end }}
        {{- end }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: udp
          containerPort: 8080
          protocol: UDP
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 2
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        {{- include "service.config" . | indent 10 }}
