apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    service: {{ .Chart.Name }}
