mongo_dsn: ENC[AES256_GCM,data:abH3XvHQgxiBvg3PRXnp+VZlYAugm2df466PnqOCebBU+QZd/9cvxpRHBYJ8Uz9VESa0Kyyvfq5AhN8W7TZL2i2glsXa,iv:jStJ0bBNarpmQyBzNGSEOa4esKvMci6S/4sgz+RCquE=,tag:nJXhVHGlrfZT/HshAfBUtw==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/gin-trading-sand/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2020-04-02T12:23:08Z'
        enc: CiQAd2NDDsBU7w5gsqDwzIGc6qduPx4h2ebEhqblgbgMYo2BmusSSACmcTzj6XMMt3gvNCcC1tIHFyaGq7ZKLfXADaxo4JlwrTwZ1P5fCxQ0yOU8So8c0PDmFmeQsff02L7Vld9x18nxsHS21Vio+w==
    azure_kv: []
    lastmodified: '2020-04-02T13:13:52Z'
    mac: ENC[AES256_GCM,data:RUxFl5+/syfrsZa/6sAqyLSvVw5otd5G2c8gVcCEWa2Qp6Ca4UYatm2LPU5uITnVNtbsekQINkTRqx1N0wF7QVg2eHhQV9d7RWuXUG22jMHjxnfLmJjc9iyR/r85bch4GYVbTTT9KiNlEqQ/3gq2R98caeH/ivXmCvvj63Ck2ks=,iv:bz+fcSXzk7II70ZcA8LgkOufEhKq5W7ErTzxOp7DKKo=,tag:m0b5c95mrImJCTcYHTeXTw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
